navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title:
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: /categories/
    - name: 标签
      icon: fas fa-tags
      url: /tags/
    - name: 归档
      icon: fas fa-archive
      url: /archives/
    - name: 友链
      icon: fas fa-link
      url: /friends/
    - name: 关于
      icon: fas fa-info-circle
      url: /about/
  # search: 搜索   # Search bar placeholder



site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:me@xxx.com
    - icon: fab fa-github
      url: https://github.com/liwensong
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=63035382
  copyright: '[Copyright © 2017-2020 Mr. X](https://xaoxuu.com)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
  hello: '[Hello World](/)'

custom_css:
  max_width: 1080px
  font_smoothing: true
