---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jenkins-pvc"
  namespace: jenkins-ns
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
