---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pv
  namespace: jenkins-ns
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
