apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: myjenkins.ztyc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-srv
            port:
              number: 8080
#  - host: myjenkins-agent.ztyc.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: jenkins-srv
#            port:
#              number: 5000
